#!/bin/sh /etc/rc.common
# Huawei Modem Telegram Bot - OpenWrt procd service
# Location: /etc/init.d/hmonn-bot

START=99
STOP=10
USE_PROCD=1

BOT_DIR="/root/bot-hmonn"
BOT_SCRIPT="$BOT_DIR/dist/index.js"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/node "$BOT_SCRIPT"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env NODE_ENV=production
    procd_set_param pidfile /var/run/hmonn-bot.pid
    procd_close_instance
}

stop_service() {
    killall node 2>/dev/null
}

reload_service() {
    stop
    start
}
